[[redirects]]
  from = "/gr-book-cover/*"
  to = "https://www.goodreads.com/book/show/:splat"
  status = 200
  force = true
  headers = {X-From = "Netlify"}
[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"